spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: marryting-profile-image
      dir: /marry
    region:
      static: ap-northeast-2
    stack:
      auto: false
